.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "TLSV1\-SCAN" "8" "March 2026" ""
.SH "NAME"
\fBTLSv1\-scan\fR \- scan local system for services using deprecated TLSv1\.0 or TLSv1\.1
.SH "SYNOPSIS"
\fBTLSv1\-scan\fR
.SH "DESCRIPTION"
\fBTLSv1\-scan\fR scans all local TCP listening ports and checks each one for TLSv1\.0 or TLSv1\.1 support using \fBsslscan(1)\fR\. For any service where those deprecated protocol versions are enabled, it reports the owning process by querying \fBss(8)\fR and \fBlsof(8)\fR\.
.P
The program must be run as root\.
.SH "DEPENDENCIES"
The following tools must be installed and available in \fBPATH\fR:
.TP
\fBsslscan\fR
Part of EPEL on RHEL\-based systems\.
.TP
\fBss\fR
Part of the \fBiproute\fR package\.
.TP
\fBlsof\fR
Part of the \fBlsof\fR package\.
.TP
\fBnetstat\fR
Part of the \fBnet\-tools\fR package\.
.SH "EXIT STATUS"
.TP
\fB0\fR
Success\.
.TP
\fB1\fR
The program was not run as root, or a required dependency was not found\.
.SH "AUTHOR"
Written by Gratien D'haese\.
.SH "SEE ALSO"
sslscan(1), ss(8), lsof(8), netstat(8)
